package uk.ac.cam.intdesign.group10.weatherapp;

import java.awt.BorderLayout;
import java.awt.Color;

import javax.swing.JComponent;
import javax.swing.JPanel;

import uk.ac.cam.intdesign.group10.weatherapp.component.TestComponent;

public class WeatherAppPanel {
    private JPanel root;
    public JPanel toolbar;
    public JPanel screenHolder;

    private void createUIComponents() {
        toolbar = new TestComponent("Toolbar", Color.blue);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        root = new JPanel();
        root.setLayout(new BorderLayout(0, 0));
        root.add(toolbar, BorderLayout.NORTH);
        screenHolder = new JPanel();
        screenHolder.setLayout(new BorderLayout(0, 0));
        root.add(screenHolder, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }
}
